import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { CartProvider } from "@/contexts/CartContext";
import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/mobile/MobileNavbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          {/* Mobile Navbar only on mobile */}
          <div className="md:hidden">
            <MobileNavbar />
          </div>
          {/* Desktop Navbar only on desktop */}
          <div className="hidden md:flex">
            <Navbar />
          </div>
          {children}
          {/* Footer only on desktop */}
          <div className="hidden md:block">
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
